### ISSUE TITLE
Export to PMML 4.1 

### ISSUE THREAD

**Issue by Ambachat** [jpmml/r2pmml#58] opened 2019-09-16 09:53 UTC
Hi,
I want to export my GBM classification model to PMML 4.1; by default it exports to version 4.3.
Can anyone help me in this, if it's possible?

**Comment by vruusmann** [comment] 2019-09-16 16:06
All JPMML conversion libraries depend on the latest version of the [JPMML-Model](https://github.com/jpmml/jpmml-model) library, which supports a fixed PMML schema version (ie. it's not possible to instruct it to generate many different schema versions). Right now, the most polular/relevant PMML schema version is 4.3, and hence this is what is generated.

If you need to upgrade/downgrade PMML schema version, then you need to write your own standalone transformation tool.

Resolution - won't fix, because everything works as intended.

**Closed by vruusmann** 2019-09-16 16:06 UTC
